### ISSUE TITLE
Run with rtx 5090

### ISSUE THREAD

**Issue by CGGUYFX** [VectorSpaceLab/OmniGen2#34]
its running by default with my cpu, how do o force it to run with my gpu?

**Comment by bfm12345** [comment]
With a 5090, you have to use the CUDA Toolkit 12.8 which is incompatible with this version of torch. Use this command instead:

pip install --pre torch torchvision torchaudio --index-url https://download.pytorch.org/whl/nightly/cu128

**Comment by DestiZ** [comment]
> when i finally got it running.. it was so slow until i saw i was running on cpu only, thanks for the suggestion will do that.

so i have a 5090 too i feel like it using for me cpu too so how did you change it to using the gpu?

**Comment by DestiZ** [comment]
> > > when i finally got it running.. it was so slow until i saw i was running on cpu only, thanks for the suggestion will do that.
> > 
> > 
> > so i have a 5090 too i feel like it using for me cpu too so how did you change it to using the gpu?
> 
> i did not yet, but in this thread someone suggested installing this https://download.pytorch.org/whl/nightly/cu128 try it and share your finding.. and you say your cpu is running also? you mean both are running how is that possible?


ouh okay i will test it, ouh i mean like you its only used for cpu at least my gpu usages was only 40% what dosent should correct at all , so i was thinking that its only using for cpu because GPU % usages was only that 40% i feel like it using GPU it have to be something like 90-95% like other local ai softwares.

**Comment by eugene-kamenev** [comment]
Docker setup for RTX 50xx:

Dockerfile (you can remove gcc g++ etc I think, libgl1 are required)

```Dockerfile
FROM pytorch/pytorch:2.7.1-cuda12.8-cudnn9-runtime

RUN apt-get update && apt-get install -y \
    build-essential \
    gcc \
    g++ \
    git \
    wget \
    curl libgl1 libglib2.0-0 \
    libgl1-mesa-glx \
    && apt-get clean && rm -rf /var/lib/apt/lists/*

# Set working directory
WORKDIR /app

RUN git clone --single-branch --depth=1 https://github.com/VectorSpaceLab/OmniGen2.git .
COPY ./requirements.txt .
RUN pip install -r requirements.txt
RUN pip install https://github.com/Dao-AILab/flash-attention/releases/download/v2.8.0.post2/flash_attn-2.8.0.post2+cu12torch2.7cxx11abiFALSE-cp311-cp311-linux_x86_64.whl
# Expose port
EXPOSE 7860

# Parameters for the startup script (if any, though CMD is now direct)
ENV MODEL_PATH=/models

# Default command to run the container
CMD ["python", "app.py", "--model_path", "/models/OmniGen2", "--server_name", "0.0.0.0"]
```

### docker-compose.yaml

```yaml
version: '3.8'
services:
  ai-omnigen2:
    build:
      context: .
      dockerfile: Dockerfile
    image: ai-omnigen2:latest
    container_name: ai-omnigen2
    ports:
      - "7893:7860"
    volumes:
      - ./models:/models
      - ./app.py:/app/app.py
    deploy:
      resources:
        reservations:
          devices:
          - driver: nvidia
            device_ids: ['0']
            capabilities: [gpu]
```

### requirements.txt
```bash
git diff requirements.txt
diff --git a/requirements.txt b/requirements.txt
index aab2103..0ad49f8 100644
--- a/requirements.txt
+++ b/requirements.txt
@@ -1,7 +1,8 @@
-torch==2.6.0
-torchvision==0.21.0
+torch>=2.6.0
+torchvision>=0.21.0
 timm
 einops
+gradio
 accelerate
 transformers==4.51.3
 diffusers
```

### app.py
```bash
git diff app.py
diff --git a/app.py b/app.py
index f37c1e0..247fb71 100644
--- a/app.py
+++ b/app.py
@@ -7,6 +7,7 @@ import gradio as gr
 import os
 import argparse
 import random
+import gc
 from datetime import datetime
 
 import torch
@@ -104,6 +105,8 @@ def run(
         output_type="pil",
         step_func=progress_callback,
     )
+    gc.collect()  # Clear memory after generation
+    torch.cuda.empty_cache()  # Clear CUDA cache
 
     progress(1.0)
 
@@ -838,6 +841,12 @@ def parse_args():
         action="store_true",
         help="Enable sequential CPU offload."
     )
+    parser.add_argument(
+        "--server_name",
+        type=str,
+        default="0.0.0.0",
+        help="network interface to publish app (127.0.0.1/0.0.0.0)"
+    )
     args = parser.parse_args()
     return args
```
